### ISSUE TITLE
removeValue always removes last value when trying to remove a nested form from dynamic field

### ISSUE THREAD

**Issue by anaspk** [react-tools/react-form#221] opened 2018-01-04 12:40 UTC
Please checkout the following form: https://codesandbox.io/s/y3ym30yzvz

What I am trying to achieve is to have a dynamic array of nested forms. So I tried to combine the [Dynamic forms](https://react-form.js.org/#/dynamic-form) example with the [Array of nested forms](https://react-form.js.org/#/array-nested-forms) example.

Clicking the "Add friend" button works correctly and it adds a new instance of the nested friend form to the end but clicking "Remove" button besides any nested form removes the last form instead of the form whose button was clicked.

Can you please point out if I am doing something wrong, or if it is a bug, or this feature is not supported at all?

Thanks.

**Comment by joepuzzo** [comment] 2018-01-07 21:50
You should not use the add remove functionality to add remove nested forms.. its not supported as of now. I would just dynamically add or remove the nested form yourself by rendering or not rendering it within the parent form.

**Comment by anaspk** [comment] 2018-01-07 22:04
Oh, I see. Is there some technical challenge involved due to which it is not supported yet? I would love to submit a PR adding support for this feature because I think it would be really useful for other users too.

> I would just dynamically add or remove the
> nested form yourself by rendering or not
> rendering it within the parent form.

Can you please provide an example of this? May be modify my codesandbox..

Thanks :-)

**Comment by joepuzzo** [comment] 2018-01-08 02:28
Stand by I'm working on your sandbox now.

**Comment by joepuzzo** [comment] 2018-01-08 13:25
Getting close to solution.. I have updated sandbox here https://codesandbox.io/s/q3xwmryyv4 it works accept for some reason you hav to retype in the field to get the value to show back up so I have to keep playing with the code.

**Comment by anaspk** [comment] 2018-01-08 13:46
That is so kind of you joepuzzo, thanks a lot :-) It looks cool.

**Comment by Jae-Huh** [comment] 2018-01-17 05:48
@anaspk @joepuzzo 

We solved this issue by passing down the removeValue function from the parent to the nested form.
e.g.

*Parent Form*
```js
          <Form onSubmit={this.onSubmit} >
            { formApi => (
              <form onSubmit={formApi.submitForm}>
                {
                  formApi.values.shows && formApi.values.shows.map((show, i) => {
                    return (
                      <SubForm key={i} index={i}
                        removeSelf={() => formApi.removeValue('shows', i)}
                      />
                    )
                  })
                }
                <button onClick={() => formApi.addValue('shows', {})}>Add Show</button>
                <button type="submit">Save</button>
              </form>
            )}
          </Form>
```

*Subform*
```js
      <NestedForm field={['shows', this.props.index]}>
        <Form>
          { formApi => (
            <div>
              <label>Field1</label>
              <Text field="field1" />
              <button onClick={this.props.removeSelf}>remove</button>
            </div>
          )}
        </Form>
      </NestedForm>
```

**Comment by Jae-Huh** [comment] 2018-01-17 05:50
Although it would be great to have this build into each formApi.removeValues(). Maybe something where if it can't find the field name, it automatically looks at its parent recursively until it finds the correct field.

**Comment by Jae-Huh** [comment] 2018-01-17 09:11
Oh. I just realised @anaspk and @joepuzzo were trying to solve a different issue.

The issue with your example was using `i` as a key. If you do this in React, when you remove the mapped vDOM element react will update the wrong DOM elements. (On a side note, would be good to update the docs so it doesn't do this. Because it WILL break for people and have unexpected behaviour.)

e.g. 3 items. key=1, key=2, key=3. All have different values. When you delete key=2, what happens is key 3 becomes key 2 (because its just `i`), and when react updates the dom it says 'Oh key=2 is still there, so there must be no changes, so I do not need to update the dom. But key=3 is missing so I better delete that'.  Even though you actually deleted key=2, and key=3 became key=2. React never looks at the actual values of what changes when using `key`.

So to fix that issue, you must give a key that doesn't change. 

Here's an update version of your demo that works as expected.
https://codesandbox.io/s/m50lq3xmjp

As you can see, I had to pass the id down as a default value, and then have it as a hidden input so that when we update the friend object it keys the id in it.

**Comment by joepuzzo** [comment] 2018-01-17 13:01
@Jae-Huh There are still issues with your sandbox. I would look at this as a guide https://codesandbox.io/s/q3xwmryyv4 . Add three fields and type firstName: foo,  firstName: bar,  firstName: baz. Then remove  firstName: bar field. Notice how it works as expected.

**Comment by Jae-Huh** [comment] 2018-01-17 14:44
@joepuzzo - I really can't decipher what's happening in that first sandbox I posted. Why on earth it creates that extra property when you remove a value.

But here is an updated version of your sandbox that **hopefully** works and doesn't require using state.

https://codesandbox.io/s/jlnm6ryq89

**Comment by joepuzzo** [comment] 2018-01-18 04:09
@Jae-Huh Wow that looks good! You are totally correct it was the key causing the issue all along. I will make a note to update docs.

**Comment by joepuzzo** [comment] 2018-02-23 18:15
V3 is out closing this issue as its resolved.

**Closed by joepuzzo** 2018-02-23 18:15 UTC
