### ISSUE TITLE
How to throw errors after submitting form ?

### ISSUE THREAD

**Issue by khotey** [react-tools/react-form#106] opened 2017-08-22 13:34 UTC
Is there a way to throw errors after submitting form ? If client validation passed and request sent to the server but server return errors validation, how throw errors to form to show in it ?

For example, like in [redux-form](http://redux-form.com/7.0.3/examples/submitValidation/):

```
const signUpAction = await signUp({
      ...data,
      termsAndConditionsId: termsAction.payload.uuid,
    });

    if (signUpAction && signUpAction.error) {
      const error = formatErrorsForReduxForm(signUpAction.payload.response);

      throw new SubmissionError({ error });
    }
```

**Comment by thg303** [comment] 2017-08-22 17:45
looks like a duplicate of #3 , you may set `refs` on your form and set the `errors` in it's state. something like this:
```
<Form 
   ref="theForm"
   onSubmit={ () => {
      callAPI().then( (success) => { ... }).catch((error) => {
         this.refs.theForm.state.errors = error;
         this.refs.theForm.setAllTouched(); // this makes the errors visible
      }) 
   }}>
{...}
</Form>
```

**Comment by tannerlinsley** [comment] 2017-10-31 03:29
This has changed slightly in version 2.0, but a ref should still do the trick to access the internal api of the component. Closing for now, but feel free to reopen or join the slack channel to get more information on how to do this. Thanks!

**Closed by tannerlinsley** 2017-10-31 03:29 UTC

**Comment by rburgst** [comment] 2024-01-02 17:10
this does not appear to work any longer. Can this still be done? I tried using `setFieldMeta` however, it appears the errors are immediately cleared out

**Comment by erickreutz** [comment] 2024-01-08 01:01
I'm also wondering about this.

**Comment by rburgst** [comment] 2024-01-08 07:40
I managed to get it working by using `setFieldMeta` and update the `errorMap`
```
      form.setFieldMeta(typedKey, (oldMeta) => ({
        ...oldMeta,
        isTouched: true,
        errorMap: { onSubmit: errorMsg as ValidationError },
      }));
```
