### ISSUE TITLE
Why is Babel-pollyfill a dependency?

### ISSUE THREAD

**Issue by nishthaarora** [react-tools/react-form#131] opened 2017-10-25 16:43 UTC
We are doing code splitting on our site and we are dynamically loading a react-form and we get this error "only one instance of babel-polyfill is allowed". As we already included in our main bundle. Please consider removing this as a dependency or if there is any workaround fro this?

**Comment by joepuzzo** [comment] 2017-10-25 16:51
Babel polyfill is there because internally react-form uses `async` `await`. If we don't include it as a dependency then it wont work for people that don't include the polyfill. I had a feeling this may be an issue but i have tested this in one of my own personal projects that also loads babel-polyfill and it has worked fine. I think the problem is the dynamic loading. I am def open to suggestions on how to resolve this as i dont know of a better solution ATM.

**Comment by joepuzzo** [comment] 2017-10-25 17:10
Maybe i need to take use somthing like https://babeljs.io/docs/plugins/transform-runtime/

**Comment by joepuzzo** [comment] 2017-10-25 17:35
I just pushed out a new version and this should be fixed!!! let me know if that worked

**Comment by nishthaarora** [comment] 2017-10-26 17:17
Can you share with us the major changes that has been done from version 1 to 2 because we are upgrading from version one to the new version and I don't see babel-pollyfill related error anymore but I am seeing some other errors.

**Comment by joepuzzo** [comment] 2017-10-26 20:16
Yeah i'm working on getting the other features added. We needed to get some bare minimums upgraded first so we had to loose some functionality to first roll out V2. I will compile a list and post it here soon.

**Comment by joepuzzo** [comment] 2017-10-26 23:15
1. V2 does not have displayed <Error> messages. If you want to display an error message you have to create a custom input via a FormField or render it below one of the base inputs (example of doing this is in docs under custom inputs ). This is because when it comes to style, I wanted to leave it up to dev to create there own <ErrorMessage> components. That being said you can always create a custom `FormField` and import that wherever you used to import <Text>.
2. V2 does not YET, have a `loadState` prop. I can probably add this, but for now it does still have the `defaultValues` prop.
3. `validate` prop is now broken up into three validation functions, [validateError, validateWarning, validateSuccess], so anywhere you had `validate` has to become `validateError`.
4. `onChange` is now `formDidUpdate` and it only receives one prop `state`. 
5. There is currently no `preSubmit` or `postSubmit` but these might be easy to add.
6. There is no such thing as `nestedErrors`. Nested forms will automatically set the parent forms errors. 
7. By default, the forms will call validate right away but you can simply pass in a dontValidateOnMount prop to prevent this.
8. V2 does not yet support setAllValues.
10. V2 does not yet have swapValues
11. V2 does not yet have setAllTouched

**Comment by joepuzzo** [comment] 2017-10-26 23:15
Also i just pushed out V2.1.0 and added some importnat features that were missing so i would give that a try now.

**Comment by casperOne** [comment] 2017-10-28 18:03
@joepuzzo What is the approach we should take in v2 in place of setAllValues?

**Comment by tannerlinsley** [comment] 2017-10-31 03:35
It looks like this issue is fixed in the latest version, so we're going to close this issue. To track progress on setAllValues, follow #122

**Closed by tannerlinsley** 2017-10-31 03:35 UTC

**Comment by hnq90** [comment] 2017-11-07 08:38
Sorry to reply in a closed issue but how can we implement `postSubmit` & `preSubmit`? I'm migrating from `react-form` v1 to v2 and I need to implement it for myself.
